routes/web.php
<?php

//dd(bcrypt('root'));
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('show-table',['uses'=>'TestController@showTable']);

Route::group(['prefix' => 'admin/', 'as' => 'admin.', 'namespace' => 'Admin\\','middleware' => 'auth'], function () {

    Route::get('dashboard',             ['as' => 'dashboard',           'uses' => 'DashboardController@index']);
    Route::get('test',                  ['as' => 'test',                'uses' => 'DashboardController@test']);

    //Route::resource('ads', 'AdsController');
    Route::get('ads',                   ['as' => 'ads.index',          'uses' => 'AdsController@index']);
    Route::get('ads/create',            ['as' => 'ads.create',         'uses' => 'AdsController@create']);
    Route::post('ads',                  ['as' => 'ads.store',          'uses' => 'AdsController@store']);
    Route::get('ads/{id}/edit',         ['as' => 'ads.edit',           'uses' => 'AdsController@edit']);
    Route::put('ads/{id}',              ['as' => 'ads.update',         'uses' => 'AdsController@update']);
    Route::delete('ads/{id}',           ['as' => 'ads.destroy',        'uses' => 'AdsController@destroy']);
    Route::delete('slider/{id}',           ['as' => 'slider.destroy',        'uses' => 'SliderController@destroy']);

    Route::resource('video','VideoController');
    Route::get('video/publish/{id}', 'VideoController@publish')->name('video.publish');
    Route::get('blogs',['as'=>'blogs.index','uses'=>'BlogController@index']);
    Route::get('blogs/create',['as'=>'blogs.create','uses'=>'BlogController@create']);
    Route::post('blogs/store',['as'=>'blogs.store','uses'=>'BlogController@store']);
    Route::get('blogs/{id}/edit',['as'=>'blogs.edit','uses'=>'BlogController@edit']);
    Route::post('blogs/{id}/update',['as'=>'blogs.update','uses'=>'BlogController@update']);
    Route::get('blogs/{id}/delete',['as'=>'blogs.delete','uses'=>'BlogController@delete']);


    Route::get('users',                 ['as' => 'users.index',         'uses' => 'UserController@index']);
    Route::get('users/create',          ['as' => 'users.create',        'uses' => 'UserController@create']);
    Route::post('users',                ['as' => 'users.store',         'uses' => 'UserController@store']);
    Route::get('users/{id}',            ['as' => 'users.show',          'uses' => 'UserController@show']);
    Route::get('users/{id}/edit',       ['as' => 'users.edit',          'uses' => 'UserController@edit']);
    Route::put('users/{id}',            ['as' => 'users.update',        'uses' => 'UserController@update']);
    Route::delete('users/{id}',         ['as' => 'users.destroy',        'uses' => 'UserController@destroy']);
    Route::get('users/profile/update',  ['as' => 'users.profile.edit', 'uses' => 'UserController@profileEdit']);
    Route::put('users/profile/update',  ['as' => 'users.profile.update', 'uses' => 'UserController@profileUpdate']);

    Route::get('roles',                 ['as' => 'roles.index',         'uses' => 'RoleController@index']);
    Route::get('roles/{id}',            ['as' => 'roles.show',          'uses' => 'RoleController@show']);
    Route::get('roles/{id}/edit',       ['as' => 'roles.edit',          'uses' => 'RoleController@edit']);
    Route::put('roles/{id}',            ['as' => 'roles.update',        'uses' => 'RoleController@update']);

   Route::resource('slider','SliderController');
   Route::get('slider/publish/{id}', 'SliderController@publish')->name('slider.publish');


});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/includes/breadcrumb.blade.php
<ul class="breadcrumb">
    <li>
        <i class="icon-home home-icon"></i>
        <a href="{{ route('admin.dashboard') }}">Home</a>
    </li>

    <li>
        <a href="{{ route('admin.blogs.index') }}">{{ $panel }}</a>
    </li>
    <li class="active">{{ $action  }}</li>
</ul><!-- .breadcrumb -->

resources/views/admin/includes/breadcrumb_sub.blade.php
<div class="page-header">
    <h1>
        {{ $panel }} Manager
        <small>
            <i class="icon-double-angle-right"></i>
            {{ $action }}
        </small>
    </h1>
</div><!-- /.page-header -->

resources/views/admin/includes/flash_messages.blade.php
@if(session()->has('success_message'))
    <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">
            <i class="icon-remove"></i>
        </button>
        {!! session()->get('success_message') !!}
    </div>
@endif


@if(session()->has('error_message'))
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">
            <i class="icon-remove"></i>
        </button>
        {!! session()->get('error_message') !!}
    </div>
@endif

resources/views/admin/includes/form_action_buttons.blade.php
<div class="col-md-offset-3 col-md-9">
    <button class="btn btn-info" type="submit" name="submit">
        <i class="icon-ok bigger-110"></i>
        Submit
    </button>&nbsp;
    <button class="btn btn-info" type="submit" name="submit-continue">
        <i class="icon-ok bigger-110"></i>
        Submit & Continue
    </button>&nbsp;&nbsp; &nbsp;
    <button class="btn" type="reset">
        <i class="icon-undo bigger-110"></i>
        Reset
    </button>
</div>

resources/views/admin/includes/form_validation_messages.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/includes/head.blade.php
<head>
    <meta charset="utf-8" />
    <title>Dashboard - Ace Admin</title>

    <meta name="description" content="overview &amp; stats" />
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- basic styles -->

    <link href="{{ asset('assets/admin-panel/css/bootstrap.min.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('assets/admin-panel/css/font-awesome.min.css') }}" />

    <!--[if IE 7]>
    <link rel="stylesheet" href="{{ asset('assets/admin-panel/css/font-awesome-ie7.min.css') }}" />
    <![endif]-->

    <!-- page specific plugin styles -->

    <!-- fonts -->

    <link rel="stylesheet" href="{{ asset('assets/admin-panel/css/ace-fonts.css') }}" />

    <!-- ace styles -->

    <link rel="stylesheet" href="{{ asset('assets/admin-panel/css/ace.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/admin-panel/css/ace-rtl.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('assets/admin-panel/css/ace-skins.min.css') }}" />

    <!--[if lte IE 8]>
    <link rel="stylesheet" href="{{ asset('assets/admin-panel/css/ace-ie.min.css') }}" />
    <![endif]-->

    <!-- inline styles related to this page -->

    <!-- ace settings handler -->

    <script src="{{ asset( 'assets/admin-panel/js/ace-extra.min.js' )}}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

    <!--[if lt IE 9]>
    <script src="{{ asset('assets/admin-panel/js/html5shiv.js') }}"></script>
    <script src="{{ asset('assets/admin-panel/js/respond.min.js') }}"></script>
    <![endif]-->
</head>

resources/views/admin/includes/header.blade.php
<div class="navbar navbar-default" id="navbar">
    <script type="text/javascript">
        try{ace.settings.check('navbar' , 'fixed')}catch(e){}
    </script>

    <div class="navbar-container" id="navbar-container">
        <div class="navbar-header pull-left">
            <a href="#" class="navbar-brand">
                <small>
                    <i class="icon-leaf"></i>
                    Ace Admin
                </small>
            </a><!-- /.brand -->
        </div><!-- /.navbar-header -->

        <div class="navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="grey">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-tasks"></i>
                        <span class="badge badge-grey">4</span>
                    </a>

                    <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-ok"></i>
                            4 Tasks to complete
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Software Update</span>
                                    <span class="pull-right">65%</span>
                                </div>

                                <div class="progress progress-mini ">
                                    <div style="width:65%" class="progress-bar "></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Hardware Upgrade</span>
                                    <span class="pull-right">35%</span>
                                </div>

                                <div class="progress progress-mini ">
                                    <div style="width:35%" class="progress-bar progress-bar-danger"></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Unit Testing</span>
                                    <span class="pull-right">15%</span>
                                </div>

                                <div class="progress progress-mini ">
                                    <div style="width:15%" class="progress-bar progress-bar-warning"></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
                                    <span class="pull-left">Bug Fixes</span>
                                    <span class="pull-right">90%</span>
                                </div>

                                <div class="progress progress-mini progress-striped active">
                                    <div style="width:90%" class="progress-bar progress-bar-success"></div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                See tasks with details
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="purple">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-bell-alt icon-animated-bell"></i>
                        <span class="badge badge-important">8</span>
                    </a>

                    <ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-warning-sign"></i>
                            8 Notifications
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-pink icon-comment"></i>
												New Comments
											</span>
                                    <span class="pull-right badge badge-info">+12</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="btn btn-xs btn-primary icon-user"></i>
                                Bob just signed up as an editor ...
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-success icon-shopping-cart"></i>
												New Orders
											</span>
                                    <span class="pull-right badge badge-success">+8</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <div class="clearfix">
											<span class="pull-left">
												<i class="btn btn-xs no-hover btn-info icon-twitter"></i>
												Followers
											</span>
                                    <span class="pull-right badge badge-info">+11</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                See all notifications
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="green">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-envelope icon-animated-vertical"></i>
                        <span class="badge badge-success">5</span>
                    </a>

                    <ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="icon-envelope-alt"></i>
                            5 Messages
                        </li>

                        <li>
                            <a href="#">
                                <img src="{{ asset('assets/admin-panel/avatars/avatar.png') }}" class="msg-photo" alt="Alex's Avatar" />
                                <span class="msg-body">
											<span class="msg-title">
												<span class="blue">Alex:</span>
												Ciao sociis natoque penatibus et auctor ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>a moment ago</span>
											</span>
										</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="{{ asset('assets/admin-panel/avatars/avatar3.png') }}" class="msg-photo" alt="Susan's Avatar" />
                                <span class="msg-body">
											<span class="msg-title">
												<span class="blue">Susan:</span>
												Vestibulum id ligula porta felis euismod ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>20 minutes ago</span>
											</span>
										</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <img src="{{ asset('assets/admin-panel/avatars/avatar4.png') }}" class="msg-photo" alt="Bob's Avatar" />
                                <span class="msg-body">
											<span class="msg-title">
												<span class="blue">Bob:</span>
												Nullam quis risus eget urna mollis ornare ...
											</span>

											<span class="msg-time">
												<i class="icon-time"></i>
												<span>3:15 pm</span>
											</span>
										</span>
                            </a>
                        </li>

                        <li>
                            <a href="inbox.html">
                                See all messages
                                <i class="icon-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="light-blue">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img class="nav-user-photo" src="{{ asset('assets/admin-panel/avatars/user.jpg') }}" alt="Jason's Photo" />
                        <span class="user-info">
									<small>Welcome,</small>
									Jason
								</span>

                        <i class="icon-caret-down"></i>
                    </a>

                    <ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                        <li>
                            <a href="#">
                                <i class="icon-cog"></i>
                                Settings
                            </a>
                        </li>

                        <li>
                            <a href="{{ route('admin.users.profile.edit') }}">
                                <i class="icon-user"></i>
                                Profile
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();"  >
                                <i class="icon-off"></i>
                                Logout
                            </a>
                            <form method="POST" action="{{ route('logout') }}" id="logout-form" style="display: none;">
                                {!! csrf_field() !!}
                            </form>
                        </li>
                    </ul>
                </li>
            </ul><!-- /.ace-nav -->
        </div><!-- /.navbar-header -->
    </div><!-- /.container -->
</div>

resources/views/admin/includes/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from 198.74.61.72/themes/preview/ace/ by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 28 Feb 2014 17:44:06 GMT -->

        @include('admin.includes.head')

<body>

        @include('admin.includes.header')

<div class="main-container" id="main-container">
    <script type="text/javascript">
        try{ace.settings.check('main-container' , 'fixed')}catch(e){}
    </script>

    <div class="main-container-inner">
        <a class="menu-toggler" id="menu-toggler" href="#">
            <span class="menu-text"></span>
        </a>

        @include('admin.includes.sidebar')

        @yield('content')

    </div><!-- /.main-container-inner -->

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>
</div><!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->

<script type="text/javascript">
    window.jQuery || document.write("<script src='{{asset('assets/admin-panel/js/jquery-2.0.3.min.js' ) }}'>"+"<"+"/script>");
</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='{{ asset('assets/admin-panel/js/jquery-1.10.2.min.js') }}'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
    if("ontouchend" in document) document.write("<script src='{{ asset('assets/admin-panel/js/jquery.mobile.custom.min.js') }}'>"+"<"+"/script>");
</script>
<script src="{{ asset('assets/admin-panel/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/admin-panel/js/typeahead-bs2.min.js') }}"></script>

<!-- page specific plugin scripts -->

@yield('extra_script_lib')

<script src="{{ asset('assets/admin-panel/js/ace-elements.min.js') }}"></script>
<script src="{{ asset('assets/admin-panel/js/ace.min.js') }}"></script>

<!-- inline scripts related to this page -->

        @yield('extra-scripts')
</body>

<!-- Mirrored from 198.74.61.72/themes/preview/ace/ by HTTrack Website Copier/3.x [XR&CO'2013], Fri, 28 Feb 2014 17:45:06 GMT -->
</html>

resources/views/admin/includes/sidebar.blade.php
<div class="sidebar" id="sidebar">
    <script type="text/javascript">
        try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
    </script>

    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
                <i class="icon-signal"></i>
            </button>

            <button class="btn btn-info">
                <i class="icon-pencil"></i>
            </button>

            <button class="btn btn-warning">
                <i class="icon-group"></i>
            </button>

            <button class="btn btn-danger">
                <i class="icon-cogs"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div><!-- #sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li {!! request()->is('admin/dashboard')?'class="active"':'' !!}>
            <a href="{{ route('admin.dashboard') }}">
                <i class="icon-dashboard"></i>
                <span class="menu-text"> Dashboard </span>
            </a>
        </li>


        <li {!! request()->is('admin/users*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-user"></i>
                <span class="menu-text"> Users </span>
                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/users')?'class="active"':'' !!}>
                    <a href="{{ route('admin.users.index') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>
                <li {!! request()->is('admin/users/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.users.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>

            </ul>
        </li>




        <li {!! request()->is('admin/roles*')?'class="active"':'' !!}>
            <a href="{{ route('admin.roles.index') }}">
                <i class="icon-group"></i>
                <span class="menu-text"> Roles </span>
            </a>
        </li>



        <li {!! request()->is('admin/slider*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-book"></i>
                <span class="menu-text"> Sliders </span>
                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/slider')?'class="active"':'' !!}>
                    <a href="{{ route('admin.slider.index') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>
                <li {!! request()->is('admin/slider/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.slider.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>



            </ul>
        </li>

        <li {!! request()->is('admin/ads*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-book"></i>
                <span class="menu-text"> Ads </span>
                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/ads')?'class="active"':'' !!}>
                    <a href="{{ route('admin.ads.index') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>
                <li {!! request()->is('admin/ads/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.ads.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>



            </ul>
        </li>
        <li {!! request()->is('admin/blogs*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-book"></i>
                <span class="menu-text"> Blogs </span>
                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/blogs')?'class="active"':'' !!}>
                    <a href="{{ route('admin.blogs.index') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>
                <li {!! request()->is('admin/blogs/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.blogs.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>



            </ul>
        </li>

         <li {!! request()->is('admin/video*')?'class="active open"':'' !!}>
            <a href="#" class="dropdown-toggle">
                <i class="icon-book"></i>
                <span class="menu-text"> Videos </span>
                <b class="arrow icon-angle-down"></b>
            </a>

            <ul class="submenu">
                <li {!! request()->is('admin/video')?'class="active"':'' !!}>
                    <a href="{{ route('admin.video.index') }}">
                        <i class="icon-double-angle-right"></i>
                        List
                    </a>
                </li>
                <li {!! request()->is('admin/video/create')?'class="active"':'' !!}>
                    <a href="{{ route('admin.video.create') }}">
                        <i class="icon-double-angle-right"></i>
                        Add
                    </a>
                </li>



            </ul>
        </li>

    </ul><!-- /.nav-list -->

    <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
    </div>

    <script type="text/javascript">
        try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
    </script>

</div>